version: 2

# 将外部预编译好的二进制文件在构建开始前复制到 dist/
before:
  hooks:
    - cp -r /tmp/build-output/* dist/

builds:
  - id: chisel
    skip: true
    binary: >-
      chisel_{{ .Os }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}

nfpms:
  - maintainer: "https://github.com/jpillora"
    formats:
      - deb
      - rpm
      - apk
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

archives:
  - formats:
      - gz
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - none*

release:
  draft: true
  replace_existing_draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
